[package]
name = "gila"
version = "0.1.0"
edition = "2021"

[lib]
name = "gila"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
deepsize = "0.2.0"
libloading = "0.8"
