[package]
name = "gila_socket"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gila = { path = ".." }
libc = "0.2.169"
windows = { version = "0.58.0", features = ["Win32_Networking_WinSock"] }
